// ******
// Exptected parameters for HTTP request to pipeline
// ******
//deployment="client01"
//vm_images_rg="vm-images-RG"
//vmss_rg="vmss_RG"
//image_name="vmimage01"
//vmss_name="testvmss"
//location="northeurope"

pipeline {
    agent any
    tools {
        "org.jenkinsci.plugins.terraform.TerraformInstallation" "terraform-0.12.6"
    }

 environment {
        TF_HOME = tool('terraform-0.12.6')
        TF_IN_AUTOMATION = "true"
        PATH = "$TF_HOME:$PATH"
        ARM_CLIENT_ID = credentials('ARM_CLIENT_ID')
        ARM_CLIENT_SECRET = credentials('ARM_CLIENT_SECRET')
        ARM_TENANT_ID = credentials('ARM_TENANT_ID')
        ARM_SUBSCRIPTION_ID = credentials('ARM_SUBSCRIPTION_ID')
    }

    node('azurevm') {
        def gitRepo = 'https://github.com/elavarez/terraform-with-jenkins-samples'
        currentBuild.result = "SUCCESS"

    try {
         stage('Init parameters'){
  
                // Get SSH public for the VMSS from Jenkins
                withCredentials([sshUserPrivateKey(credentialsId: 'public-key-id', keyFileVariable: 'PUBLICKEY')]) {
                        sh  """
                        mkdir /home/jenkins/.ssh
                        cat $PUBLICKEY >/home/jenkins/.ssh/id_rsa.pub
                        """
  
            }
         }
         stage('Checkout'){
 
                // Get the terraform plan
                git url: gitRepo, branch: 'master'
 
        }
        stage('Terraform init'){

                // Initialize the plan 
                sh  """
                    cd terraform-plans/create-vmss-from-image
                    terraform init -input=false
                   """

        }
        stage('Terraform plan'){

                
                // Get the VM image ID for the VMSS  
                sh  '''
                     az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
                    '''

                image_id = sh (
                            script: "az image show -g $vm_images_rg -n $image_name --query '{VMName:id}' --out tsv",
                            returnStdout: true).trim()

                sh (script:"cd terraform-plans/create-vmss-from-image && terraform plan -out=tfplan -input=false -var 'terraform_resource_group='$vmss_rg -var 'terraform_vmss_name='$vmss_name -var 'terraform_azure_region='$location -var 'terraform_image_id='$image_id")
                     

        }
       
        stage('Terraform apply'){

                // Apply the plan
                sh  """  
                    cd terraform-plans/create-vmss-from-image
                    terraform apply -input=false -auto-approve "tfplan"
                   """

        }
        stage('Upload tfstate'){

                // Upload the state of the plan to Azure Blob Storage
                sh (script: "cd terraform-plans/create-vmss-from-image && tar -czvf ~/workspace/${env.JOB_NAME}/$deployment'.tar.gz' .")
                sh "pwd"
                azureUpload blobProperties: [cacheControl: '', contentEncoding: '', contentLanguage: '', contentType: '', detectContentType: true], containerName: '<container-name>', fileShareName: '', filesPath: '${deployment}.tar.gz', storageCredentialId: '<jenkins-storage-id>', storageType: 'blobstorage'
                

        }
    }
    catch (err) {
        currentBuild.result = "FAILURE"
        throw err
    }
    }
}
